### ISSUE TITLE
How to get and use the data from this extension.

### ISSUE THREAD

**Issue by terlan4** [deshaw/jupyterlab-execute-time#104]
Hi, I would love to be able print the output of this extension after each cell execution. I probably need `NotebookActions.selectionExecuted` to listen to cell executions. But then how I am going to show cell source code together with execution time result of the cell?

![image](https://github.com/deshaw/jupyterlab-execute-time/assets/138553763/e78a385c-3e5a-48fa-a109-8e52c1d43a33)

**Comment by krassowski** [comment]
This extension re-uses the timing information stored in cell metadata when `recordTiming` option of `@jupyterlab/notebook-extension:tracker` is enabled. You can obtain the metadata using JupyterLab APIs or directly from the notebook file.

As this is not an issue in jupyterlab-execute-time extension, should we close this issue?

**Comment by krassowski** [comment]
> will I access to that kind of cell metadata from NotebookActions.selectionExecuted? 

Yes, because it emits the `lastCell` of `Cell` type (if you want the data for the last cell). You can then obtain the metadata the same way as this extension does:

https://github.com/deshaw/jupyterlab-execute-time/blob/4655593743606a55c5e07f35f8dfb8c300f0a67d/src/ExecuteTimeWidget.ts#L172

In general [Jupyter Community Forum](https://discourse.jupyter.org/c/jupyterlab/extensions/43) may be a better place to ask questions like this.

> Other than that, yes we can close this, Thank you very much.

Closing as per above, thanks!
