### ISSUE TITLE
Time in cell seems to fluctuate a span of twenty minutes multiple times a second

### ISSUE THREAD

**Issue by jabbera** [deshaw/jupyterlab-execute-time#111]
Sorry of the description is odd, but I didn't know how to explain it.

https://github.com/deshaw/jupyterlab-execute-time/assets/301208/ea199936-435b-4415-9a98-d24ef1884c9a

jupyterlab_execute_time   3.1.0              pyhd8ed1ab_0    conda-forge

**Comment by krassowski** [comment]
@jabbera thanks for opening the issue. I saw something similar in the past when the kernel crashes (https://github.com/deshaw/jupyterlab-execute-time/issues/84) and I believe that was already fixed in https://github.com/deshaw/jupyterlab-execute-time/pull/100 but the fix is only effective in JupyterLab 4.1+ (currently in release candidate phase). Which version of JupyterLab did you use?

In general, can you provide reproduction instructions, or does it happen sporadically without a clear trigger?

Finally, do you have windowing enabled in JupyterLab settings (Settings → Settings Editor → Notebook → Windowing mode, at the very bottom)?

FYI, there is a newer version (3.1.1) available.

**Comment by mlucool** [comment]
I am seeing this with defer + 4.1.0rc1

**Comment by krassowski** [comment]
I can reproduce when re-running a cell which was already running. There is an error in the console:

```ts
ExecuteTimeWidget.ts:311 Uncaught TypeError: Cannot read properties of undefined (reading 'execution_failed')
    at ExecuteTimeWidget.ts:311:34
```

so this is a regression from the PR I mentioned. I will open a PR to fix it.

**Comment by krassowski** [comment]
@jabbera if you would like to test the fix from https://github.com/deshaw/jupyterlab-execute-time/pull/112, you can download `extension-artifacts` from [the associated CI build](https://github.com/deshaw/jupyterlab-execute-time/actions/runs/7756720016) and install the patched version using `pip`.

**Comment by mlucool** [comment]
This was released
