### ISSUE TITLE
Validation failed

### ISSUE THREAD

**Issue by czcindy426** [deshaw/jupyterlab-execute-time#81]
Hi,

When I installed this extension, I got an error of 'validation failed'. The log file gives the following error message. 

A `_jupyter_server_extension_points` function was not found in jupyterlab_execute_time. 

According to the Jupiter server documentation, [this function is required for an extension to be discoverable](https://jupyter-server.readthedocs.io/en/latest/developers/extensions.html). 
<img width="988" alt="Screen Shot 2023-03-03 at 9 37 15 AM" src="https://user-images.githubusercontent.com/42990122/223227576-c0cf02b0-bc59-456a-bfc6-659d82321356.png">

The version of JupyterLab I'm using is 3.6.1. 

Can you resolve this issue?
Thanks!

**Comment by krassowski** [comment]
`jupyterlab-execute-time` is not a server extension and it should not be on this list in the first place. One way it could have appeared there was if one invoked:

```
jupyter server extension enable jupyterlab_execute_time
```

which is **incorrect**. To recover you can find a file where the server config was saved (likely `jupyter_server_config.d/jupyterlab_execute_time.json` in one of the configuration paths, see `jupyter --paths`) and remove it. If you do need to manually enable this extension (because it was previously disabled) please use:

```
jupyter labextension enable jupyterlab_execute_time
```

For more context on this warning please see https://github.com/jupyter-server/jupyter_server/issues/1228#issuecomment-1456800479.

If you can provide a reproducible instruction for this problem which does not involve `jupyter server extension enable` this would be very interesting and worth a follow up.

**Comment by krassowski** [comment]
Hi @czcindy426 did the explanation above help to resolve your issue?

**Comment by mlucool** [comment]
Closing as inactive.

**Comment by czcindy426** [comment]
> 

Hi @krassowski Thank you for your reply and sorry for replying to you so late. I eventually chose to install everything in condo environment and did not run into any issues whatsoever...
