### ISSUE TITLE
execute-time seems to keep running after the jupyter kernel dies.

### ISSUE THREAD

**Issue by dharhas** [deshaw/jupyterlab-execute-time#84]
No sure if this is jupyterhub specific or a general issue. But if the jupyter-kernel dies for any reason the time ticker keeps going and the cell looks like it is still running. The asterisk at the side of the cell also still shows the cell as running. Has anyone else experienced this?

**Comment by krassowski** [comment]
Yes, I experienced this a few times. I suspect that the underlying issue is the same as in https://github.com/jupyterlab/jupyterlab/issues/13780 which I fixed in https://github.com/jupyterlab/jupyterlab/pull/13832. Shortly, when kernel gets killed (e.g. by OOM killer) it does not send the message saying that it died (well, it can't - it's dead); instead we can listen to `restarting` message which indicates that a new kernel is being spawn in place of the old one and use it to mark execution as finished.

**Comment by mlucool** [comment]
> we can listen to restarting message which indicates that a new kernel is being spawn in place of the old one and use it to mark execution as finished

We may just want to mark this as failed not finished in some way. Other than that, I agree

**Comment by mlucool** [comment]
@krassowski is this still an issue? If so, lets fix it

**Comment by krassowski** [comment]
Yes.

This also happens when cutting and pasting, or when dragging cells while the execution is running:

![keeps-running](https://github.com/deshaw/jupyterlab-execute-time/assets/5832902/60b4c6c8-34c2-4b7c-bbca-07322f04e9a7)
