### ISSUE TITLE
Conda environment crashed after installing jupyterlab_execute_time using pip

### ISSUE THREAD

**Issue by BetaGem** [deshaw/jupyterlab-execute-time#96]
After running `pip install jupyterlab_execute_time`, pip installed many dependencies, including `arrow async-lru attrs babel fqdn isoduration jinja2 jsonschema jsonschema-specifications jupyter_client jupyter_core jupyter_events jupyter-lsp jupyter_server jupyter_server_terminals jupyterlab jupyterlab_server notebook-shim overrides platformdirs python-json-logger pyzmq referencing requests rfc3339-validator rfc3986-validator rpds-py send2trash tornado traitlets uri-template webcolors`. 

Then lots of conflicts occurred in my conda environment.

**Comment by krassowski** [comment]
This is expected because jupyterlab-execute-time depends on JupyterLab, and the dependencies you list are mostly JupyterLab dependencies. When you use pip with conda it may lead to conflicts, especially if pip was not previously explicitly installed in the conda environment.

If you are using a conda environment you should install with conda, not pip. There are instructions for installing jupyterlab-execute-time with conda [in the README](https://github.com/deshaw/jupyterlab-execute-time#install). As such this is not an issue in jupyterlab-execute-time.

**Comment by BetaGem** [comment]
@krassowski I see. Thanks a lot!
